"""No-pytest test runner for the carryover-aware supervisory-control suite.

Runs every ``test_*`` function across the test modules and reports a summary. Exits non-zero
if any test fails, so it works as a CI gate without pytest::

    python -m vla_lab.tests.run_tests                 # the live suite
    python -m vla_lab.tests.run_tests --archived      # + the archived rehab Phase 0 suite
    python -m vla_lab.tests.run_tests --only test_supervisory_carryover

The archived modules live in ``vla_lab/old_direction/tests/`` and cover the pre-pivot
arm-choice track. They are kept runnable (nothing was deleted) but are off the default gate
because the live direction no longer depends on them.
"""

from __future__ import annotations

import argparse
import importlib
import sys
from pathlib import Path
from typing import List, Tuple

from vla_lab.tests import run_namespace

#: (import path, module name) for the live direction.
MODULES: List[str] = [
    # --- shared inference / interaction utilities carried through the pivot ---
    "test_allocation",
    "test_calibration",
    "test_human_study",
    "test_fit_allocator",
    "test_feedback",
    "test_intent",
    "test_multicam",
    # --- carryover-aware supervisory control (the live direction) -------------
    "test_supervisory_scenes",
    "test_supervisory_physics_fit",
    "test_supervisory_carryover",
    "test_supervisory_estimand",
    "test_supervisory_scheduler",
    "test_supervisory_supervisor",
    "test_supervisory_protocol",
    "test_supervisory_session",
    "test_supervisory_logging",
    "test_supervisory_models",
    "test_policy_grounder",
    "test_supervisory_audit",
]

ARCHIVED_MODULES: List[str] = [
    "test_rehab_workspace",
    "test_rehab_carryover",
    "test_rehab_estimand",
    "test_rehab_scheduler",
    "test_rehab_sim_participant",
    "test_rehab_protocol",
    "test_rehab_safety",
    "test_rehab_logging",
    "test_rehab_observation",
    "test_rehab_session",
]


def _collect(args: argparse.Namespace) -> List[Tuple[str, str]]:
    """-> [(package, module)] to run, in order."""
    picks: List[Tuple[str, str]] = [("vla_lab.tests", m) for m in MODULES]
    if args.archived or args.archived_only:
        arch = [("vla_lab.old_direction.tests", m) for m in ARCHIVED_MODULES]
        picks = arch if args.archived_only else picks + arch
    if args.only:
        wanted = set(args.only)
        picks = [p for p in picks if p[1] in wanted]
    return picks


def main(argv: List[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--archived", action="store_true", help="also run the archived rehab Phase 0 suite")
    ap.add_argument("--archived-only", action="store_true", help="run ONLY the archived suite")
    ap.add_argument("--only", nargs="+", metavar="MODULE", help="run only these test modules")
    ap.add_argument("--count", action="store_true",
                    help="print the number of tests in the live suite (and the archived one) without running them; "
                         "the paper build reads this so the manuscript never hand-writes a test count")
    ap.add_argument("--count-tex", type=Path, default=None,
                    help="with --count: also write \\newcommand macros (NTests, NArchivedTests) to this file")
    args = ap.parse_args(argv)

    if args.count:
        counts = {}
        for label, mods, pkg in (("live", MODULES, "vla_lab.tests"), ("archived", ARCHIVED_MODULES, "vla_lab.old_direction.tests")):
            n = 0
            for mod_name in mods:
                try:
                    mod = importlib.import_module(f"{pkg}.{mod_name}")
                except ModuleNotFoundError:
                    continue
                n += sum(1 for k in dir(mod) if k.startswith("test_") and callable(getattr(mod, k)))
            counts[label] = n
        print(f"live: {counts['live']}   archived: {counts['archived']}")
        if args.count_tex:
            args.count_tex.parent.mkdir(parents=True, exist_ok=True)
            args.count_tex.write_text("% generated by vla_lab.tests.run_tests --count -- do not edit by hand\n"
                                      f"\\newcommand{{\\NTests}}{{{counts['live']}}}\n"
                                      f"\\newcommand{{\\NArchivedTests}}{{{counts['archived']}}}\n")
        return 0

    picks = _collect(args)
    total_failed = 0
    total_run = 0
    missing: List[str] = []
    for pkg, mod_name in picks:
        try:
            mod = importlib.import_module(f"{pkg}.{mod_name}")
        except ModuleNotFoundError as exc:
            # A module listed but not yet written is a build-order fact, not a test failure;
            # surface it loudly at the end rather than aborting the whole gate.
            if mod_name in str(exc):
                missing.append(f"{pkg}.{mod_name}")
                continue
            raise
        ns = {k: getattr(mod, k) for k in dir(mod)}
        n_tests = sum(1 for k in ns if k.startswith("test_") and callable(ns[k]))
        total_run += n_tests
        total_failed += run_namespace(ns, label=mod_name)

    print("\n" + "=" * 60)
    if missing:
        print(f"[SKIP] {len(missing)} listed module(s) not present: {', '.join(missing)}")
    status = "OK" if total_failed == 0 else "FAILED"
    n_mod = len(picks) - len(missing)
    print(f"[{status}] {total_run - total_failed}/{total_run} tests passed across {n_mod} modules")
    return 1 if total_failed else 0


if __name__ == "__main__":
    sys.exit(main())
