"""Datasets for the Carryover-Aware VLA.

Two kinds of sample, deliberately kept in one loader so a batch can mix them:

**Dialogue samples** teach the intent heads and the ask gate. They are generated by running the
real session machinery against generative supervisors, so every sample carries exactly the
context a deployed system would have: the scene image, the utterance, and the belief module's
own estimate of the residue. Generating rather than replaying a fixed corpus means the training
distribution is reproducible from a seed and can be re-drawn when the contract changes.

**Manipulation samples** teach the action head, from the scripted experts' rollouts. Without
them the policy grounds instructions it cannot execute, and every regret number is fiction.

Three label subtleties, each of which would quietly wreck the experiment if got wrong:

``unprompted``
    The reference label is **a fresh uncontaminated draw from the same supervisor**, not their
    true probability. That is what a no-coach reference block actually gives you: one noisy
    Bernoulli sample. Training on the true probability would hand the model a supervision signal
    no study can produce and inflate every de-biasing number.
``ask_label``
    A **soft** target: the probability that a counter-proposal would have changed the answer,
    computed from the two response probabilities. Thresholding it to a hard label throws away
    exactly the gradation the gate needs, and labelling it "was kappa big" would teach the head
    a rule the belief module already applies.
``kappa``
    The **belief module's estimate**, not the simulator's true residue. A model trained on the
    true residue learns to trust a number it will never see again.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import torch
from torch.utils.data import Dataset

from ..dataset import TinyTokenizer
from ..policy.context import CONTEXT_DIM, CONTEXT_TEXT, CarryoverContext
from ..policy.carryover_vla import prepare_instruction
from ..supervisory import COACH, COUNTER, PROBE, STRATEGY_A, STRATEGY_B
from ..supervisory.apparatus import LexicalGrounder, SimulatedSupervisorChannel, SurrogateApparatus
from ..supervisory.contract import Contract
from ..supervisory.narration import probe_query
from ..supervisory.protocol import build_protocol
from ..supervisory.scheduler import COMPARED_CONDITIONS, CONDITION_NO_COACH, build_scheduler
from ..supervisory.session import run_block
from ..supervisory.strategies import get_axis
from ..supervisory.supervisor import SimulatedSupervisor, SupervisorPopulation, draw_supervisor
from .scene_atlas import SceneAtlas

STRATEGY_TO_CLASS = {STRATEGY_A: 0, STRATEGY_B: 1}


@dataclass
class DialogueSample:
    scene_id: int
    instruction: str
    said: int
    unprompted: int
    ask_label: float
    context: CarryoverContext
    kappa: float
    rho: float
    beta: float
    condition: str
    supervisor_id: str
    #: Ground truth, for analysis only. Never fed to the model.
    truth: Dict[str, Any] = field(default_factory=dict)


def generate_dialogues(
    *,
    contract: Optional[Contract] = None,
    n_supervisors: int = 40,
    seed: int = 0,
    population: Optional[SupervisorPopulation] = None,
    conditions: Optional[Sequence[str]] = None,
    doses: Optional[Sequence[str]] = None,
) -> List[DialogueSample]:
    """Run sessions and harvest one sample per answered slot.

    A **mixture of conditions** is used rather than a single one, because the training
    distribution over the residue is what the intent head sees at deployment: a model trained
    only on always-probe sessions never sees a cleanly-washed-out answer, and one trained only
    on fixed-washout sessions never sees a heavily contaminated one. Both regimes have to be in
    the data or the de-biasing head is fitted on half the problem.
    """
    contract = contract or Contract()
    conds = list(conditions) if conditions else list(COMPARED_CONDITIONS)
    # Mix the dose ladder. A head trained only at the pre-registered dose has never seen a
    # heavily contaminated instruction and cannot de-bias one; a head trained only at the strong
    # dose over-corrects everything. The evaluation population is unchanged -- this widens the
    # training distribution, it does not move the test.
    dose_list = list(doses) if doses else [contract.dose]
    axis = get_axis(contract.axis)
    grounder = LexicalGrounder(contract.axis)
    rng = random.Random(int(seed))
    out: List[DialogueSample] = []

    for i in range(int(n_supervisors)):
        params = draw_supervisor(rng, population, supervisor_id=f"T{i:03d}")
        contract.dose = dose_list[i % len(dose_list)]
        protocol = build_protocol(
            supervisor_id=params.supervisor_id, contract=contract, seed=int(seed) + i,
            conditions=conds, order_index=i,
        )
        cond = conds[i % len(conds)]
        blk = protocol.condition_blocks()[0]
        blk.condition = cond
        sup = SimulatedSupervisor(params, axis=contract.axis, cfg=contract.carryover, seed=int(seed) + i)
        sch = build_scheduler(
            cond, contract.grid, carryover_cfg=contract.carryover,
            delta_model=contract.delta_model(), seed=int(seed) + i,
        )
        res = run_block(
            contract=contract, block=blk, apparatus=SurrogateApparatus(contract.grid, seed=int(seed) + i),
            channel=SimulatedSupervisorChannel(sup), grounder=grounder, scheduler=sch, seed=int(seed) + i,
        )

        # Replay the block to recover, per answered slot, the belief the policy held at the
        # time. Replaying rather than logging keeps this in step with the scheduler by
        # construction: if the belief update changes, the training features change with it.
        belief = build_scheduler(
            cond, contract.grid, carryover_cfg=contract.carryover,
            delta_model=contract.delta_model(), seed=int(seed) + i,
        )
        belief.reset(blk.budget)
        recent: List[Tuple[str, int, bool]] = []
        cold = SimulatedSupervisor(params, axis=contract.axis, cfg=contract.carryover, seed=int(seed) + 9000 + i)
        from ..supervisory.scheduler.base import HistoryRecord

        for r in res.records:
            scene = contract.grid.by_id(int(r["scene_id"]))
            if r["action"] in (PROBE, COUNTER) and r.get("instructed_strategy") in (STRATEGY_A, STRATEGY_B):
                m = belief.posterior.mean() if hasattr(belief, "posterior") else {}
                cont = belief.posterior.contamination() if hasattr(belief, "posterior") else {"mean": 0.0, "sd": 0.0}
                ctx = CarryoverContext(
                    kappa=float(cont.get("mean", 0.0)),
                    kappa_sd=float(cont.get("sd", 0.0)),
                    lambda_hat=float(m.get("lambda", 0.5)),
                    beta_g_hat=float(m.get("beta_g", 0.0)),
                    slots_since_coach=int(_since_coach(res.records, int(r["slot"]))),
                    recent=tuple(recent[:4]),
                    scene_c=float(scene.c),
                )
                # The ask gate's target is the **value** of counter-proposing here: how much
                # closer to the supervisor's unprompted preference the answer would come if the
                # closed option were re-opened. Two weaker targets were rejected. "Would the
                # answer change" peaks wherever the scene is ambiguous, whether or not the
                # change is an improvement, so a gate trained on it learns to ask hardest
                # exactly where asking is least informative. "Is kappa large" is a rule the
                # belief module already applies, so a head that learned it would add nothing.
                pi = sup.pi_star(scene)
                p_probe = _p_a(sup, scene, PROBE, contract)
                p_counter = _p_a(sup, scene, COUNTER, contract)
                flip = max(0.0, abs(p_probe - pi) - abs(p_counter - pi))
                cold_answer = cold.respond(scene, action=PROBE, session_progress=0.0)
                out.append(
                    DialogueSample(
                        scene_id=int(scene.scene_id),
                        instruction=str(r.get("utterance", "")),
                        said=STRATEGY_TO_CLASS[str(r["instructed_strategy"])],
                        unprompted=STRATEGY_TO_CLASS[str(cold_answer.strategy)],
                        ask_label=float(flip),
                        context=ctx,
                        kappa=float(cont.get("mean", 0.0)),
                        rho=float(contract.carryover.rho_for(r["action"])),
                        beta=float(m.get("beta", 1.0)),
                        condition=cond,
                        supervisor_id=params.supervisor_id,
                        truth={"pi_star": float(pi), "kappa_true": float(sup.kappa_eff),
                               "p_probe": float(p_probe), "p_counter": float(p_counter),
                               "beta_true": float(params.beta), "c": float(scene.c)},
                    )
                )
            if r["action"] == COACH:
                recent.insert(0, (str(r.get("demonstrated_strategy", STRATEGY_A)), 0, bool(r.get("repeats", 1))))
                recent = [(s, a + 1, n) for s, a, n in recent]
            belief.observe(
                HistoryRecord(
                    slot=int(r["slot"]), action=str(r["action"]), scene_id=int(r["scene_id"]),
                    delta=float(r["delta"]), coach_direction=int(r["coach_direction"]),
                    coach_strength=float(r["coach_strength"]), instructed=r.get("instructed_strategy"),
                    c=float(r["c"]), clutter=int(r["clutter"]), duration_s=float(r.get("duration_s", 0.0)),
                )
            )
    return out


def _since_coach(records: Sequence[Dict[str, Any]], slot: int) -> int:
    n = 0
    for r in reversed([x for x in records if int(x["slot"]) < slot]):
        if r["action"] == COACH:
            return n
        n += 1
    return 99


def _p_a(sup: SimulatedSupervisor, scene, action: str, contract: Contract) -> float:
    """The supervisor's response probability without consuming randomness."""
    pi = sup.pi_star(scene)
    rho = contract.carryover.rho_for(action)
    eta = math.log(max(pi, 1e-9) / max(1.0 - pi, 1e-9)) + rho * float(sup.p.beta) * sup.kappa_eff
    return 1.0 / (1.0 + math.exp(-eta))


class SupervisoryDialogueDataset(Dataset):
    """Torch dataset over :class:`DialogueSample`, with images from the scene atlas."""

    def __init__(
        self,
        samples: Sequence[DialogueSample],
        *,
        contract: Optional[Contract] = None,
        atlas: Optional[SceneAtlas] = None,
        context_mode: str = "token",
        context_style: str = "rich",
        image_size: int = 224,
        tokenizer: Optional[TinyTokenizer] = None,
        max_lang_len: int = 32,
        state_dim: int = 4,
        chunk_len: int = 8,
        action_dim: int = 7,
        seed: int = 0,
    ) -> None:
        self.samples = list(samples)
        self.contract = contract or Contract()
        self.context_mode = str(context_mode)
        #: ``rich`` or ``compact``. Backbones with a tight instruction budget must use
        #: ``compact``; see :meth:`prompt_length_report`, which is what catches it when they do
        #: not, because silent truncation looks like "the architecture did not help".
        self.context_style = str(context_style)
        self.axis = get_axis(self.contract.axis)
        self.atlas = atlas or SceneAtlas(self.contract.grid, size=image_size)
        self.context_mode = str(context_mode)
        # The tokenizer's vocabulary is built from THIS dataset's own instructions plus the
        # verbalised contexts, because in `text` mode the context is part of the prompt and a
        # vocabulary built only from utterances would map every context word to <unk> -- which
        # would make the text mode look like it does not work when in fact it was never given
        # the words. Saved with the checkpoint so eval reconstructs identical ids.
        self.max_lang_len = int(max_lang_len)
        if tokenizer is None:
            corpus = [self._prompt(x) for x in self.samples] or ["pick up the target"]
            tokenizer = TinyTokenizer.build_from_corpus(corpus, max_len=self.max_lang_len, max_vocab=2048)
        self.tokenizer = tokenizer
        self.state_dim = int(state_dim)
        self.chunk_len = int(chunk_len)
        self.action_dim = int(action_dim)
        self._rng = np.random.default_rng(int(seed))

    def __len__(self) -> int:
        return len(self.samples)

    def _prompt(self, sample: DialogueSample) -> str:
        """The exact string the model sees. One implementation, used by the vocabulary build,
        by ``__getitem__``, and by evaluation -- prompt drift between training and deployment is
        the classic silent failure of text-conditioned policies."""
        return prepare_instruction(
            sample.instruction, sample.context, self.context_mode,
            axis_labels=(self.axis.label_a, self.axis.label_b),
            compact=(self.context_style == "compact"),
        )

    def __getitem__(self, idx: int) -> Dict[str, Any]:
        s = self.samples[int(idx)]
        img, src = self.atlas.image(s.scene_id, rng=self._rng)
        prompt = self._prompt(s)
        ids, mask = self.tokenizer.encode(prompt)
        return {
            # The prompt as text, for backbones with a real tokenizer of their own. The
            # tokenised form below is only for the from-scratch backbone's own embedding table;
            # a pretrained VLA must be given the string, or it trains on nothing at all.
            "prompt": prompt,
            "image": torch.from_numpy(img),
            "state": torch.zeros(self.state_dim),
            "lang_ids": torch.as_tensor(ids, dtype=torch.long),
            "lang_mask": torch.as_tensor(mask, dtype=torch.long),
            "context": torch.tensor(s.context.features(), dtype=torch.float32),
            "kappa": torch.tensor(float(s.kappa)),
            "rho": torch.tensor(float(s.rho)),
            "beta": torch.tensor(float(max(s.beta, 1e-3))),
            "said": torch.tensor(int(s.said), dtype=torch.long),
            "said_mask": torch.tensor(1.0),
            "unprompted": torch.tensor(int(s.unprompted), dtype=torch.long),
            "unprompted_mask": torch.tensor(1.0),
            "ask_label": torch.tensor(float(s.ask_label)),
            "ask_mask": torch.tensor(1.0),
            "action": torch.zeros(self.chunk_len, self.action_dim),
            "action_mask": torch.tensor(0.0),
            # Analysis-only. Never given to the model -- it is the quantity being estimated.
            # Carried in the batch so validation can score the head's probability against the
            # supervisor's true unprompted preference instead of against one noisy draw of it,
            # which is mostly Bernoulli noise and swamps the effect being measured.
            "pi_star": torch.tensor(float(s.truth.get("pi_star", 0.5))),
            "kappa_true": torch.tensor(float(s.truth.get("kappa_true", 0.0))),
            "image_source": src,
            "scene_id": int(s.scene_id),
            "supervisor_id": s.supervisor_id,
        }


    def prompt_length_report(self, tokenizer, *, budget: int, n: int = 400) -> Dict[str, Any]:
        """How many prompts this dataset would lose to truncation under ``budget`` tokens.

        Run before training, not after. A prompt that overflows its budget is not a small loss
        of context: SmolVLM's tokenizer truncates from the **left**, so the overflow eats the
        beginning of the context -- which strategy was demonstrated and how often -- while the
        instruction at the end survives. The model then trains on a context stub, learns
        nothing from it, and the run looks like evidence that verbalised context does not work.
        It cost exactly one such false result to find this.
        """
        import numpy as np

        take = self.samples[: int(n)]
        lens = [len(tokenizer(self._prompt(s))["input_ids"]) for s in take]
        over = [l for l in lens if l > int(budget)]
        return {
            "budget": int(budget),
            "style": self.context_style,
            "mode": self.context_mode,
            "n_checked": len(lens),
            "mean_tokens": float(np.mean(lens)) if lens else 0.0,
            "p95_tokens": float(np.percentile(lens, 95)) if lens else 0.0,
            "max_tokens": int(max(lens)) if lens else 0,
            "n_truncated": len(over),
            "frac_truncated": float(len(over) / max(len(lens), 1)),
            "ok": len(over) == 0,
        }


def collate(batch: Sequence[Dict[str, Any]]) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    for k in batch[0]:
        v = batch[0][k]
        if isinstance(v, torch.Tensor):
            out[k] = torch.stack([b[k] for b in batch])
        else:
            out[k] = [b[k] for b in batch]
    return out


__all__ = [
    "DialogueSample",
    "SupervisoryDialogueDataset",
    "generate_dialogues",
    "collate",
    "STRATEGY_TO_CLASS",
]
