"""Emit the manuscript's result tables as LaTeX fragments, straight from the result files.

Every number in a paper that a person copied out of a JSON file by hand is a number that can
silently disagree with the run it claims to come from. Re-running an experiment and forgetting
to update one cell leaves no trace: the table still compiles, the caption still reads correctly,
and the error survives review. So the tables that carry measurements are generated.

    python -m vla_lab.supervisory.latex_tables

Writes ``tab_models.tex``, ``tab_deployed.tex`` and ``tab_sensitivity.tex`` into the paper's
``tables/`` directory, each with a provenance comment naming the file and its modification time.
The manuscript ``\\input``s them, so a stale table is impossible rather than merely unlikely.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

PAPER = Path("vla_lab/paper/hri2027_carryover_vla")


def _stamp(src: Path) -> str:
    when = _dt.datetime.fromtimestamp(src.stat().st_mtime).strftime("%Y-%m-%d %H:%M") if src.exists() else "MISSING"
    return f"% generated by vla_lab.supervisory.latex_tables from {src} ({when})\n% do not edit by hand\n"


def _f(x: Any, nd: int = 4, signed: bool = False) -> str:
    try:
        v = float(x)
    except (TypeError, ValueError):
        return "--"
    if v != v:                       # NaN
        return "--"
    return f"${v:+.{nd}f}$" if signed else f"${v:.{nd}f}$"


#: Context modes in the order the paper discusses them, so the table reads the same for every
#: backbone regardless of which order the sweep happened to run them in.
CONTEXT_ORDER = {"none": 0, "text": 1, "token": 2, "film": 3}


def models_table(src: Path, extra: Sequence[Path] = ()) -> str:
    """The architecture comparison: one row per (backbone, context mode).

    Takes several ``table.json`` files -- one per backbone sweep -- and merges them, so adding a
    backbone to the roster is a matter of running its sweep rather than editing LaTeX.
    """
    rows: List[Dict[str, Any]] = []
    for p in [src, *extra]:
        if Path(p).exists():
            rows.extend(json.loads(Path(p).read_text()))
    by_model: Dict[str, List[Dict[str, Any]]] = {}
    for r in rows:
        if r.get("debias_gain_brier") is None:       # a cell that failed to train
            continue
        by_model.setdefault(str(r.get("display", r.get("model", "?"))), []).append(r)
    for cells in by_model.values():
        cells.sort(key=lambda c: CONTEXT_ORDER.get(str(c.get("context")), 9))

    out = [_stamp(src), "\\begin{tabular}{@{}llrrrr@{}}", "\\toprule",
           "Backbone & Context & Trainable & Gain (Brier) & gap$\\sim\\kappa$ & ask $\\rho$ \\\\", "\\midrule"]
    for i, (display, cells) in enumerate(by_model.items()):
        if i:
            out.append("\\midrule")
        best_gain = max((c.get("debias_gain_brier", float("-inf")) for c in cells), default=None)
        best_corr = max((c.get("debias_kappa_corr", float("-inf")) for c in cells), default=None)
        out.append(f"\\multirow{{{len(cells)}}}{{*}}{{{display}}}")
        for c in cells:
            g, k = c.get("debias_gain_brier"), c.get("debias_kappa_corr")
            gs = _f(g, 3, signed=True)
            ks = _f(k, 3, signed=True)
            if g is not None and g == best_gain:
                gs = f"$\\mathbf{{{float(g):+.3f}}}$"
            if k is not None and k == best_corr:
                ks = f"$\\mathbf{{{float(k):+.3f}}}$"
            n, tot = c.get("params_trainable"), c.get("params_total")
            if not isinstance(n, (int, float)):
                npretty = "--"
            elif isinstance(tot, (int, float)) and tot > 1.5 * n:
                # LoRA rows: the trainable count alone reads as though the model were small.
                npretty = f"{n / 1e6:.1f}\\,M / {tot / 1e9:.1f}\\,B"
            else:
                npretty = f"{n / 1e6:.1f}\\,M"
            out.append(f" & \\textsf{{{c.get('context', '?')}}} & {npretty} & {gs} & {ks} "
                       f"& {_f(c.get('ask_rank_corr'), 3, signed=True)} \\\\")
    out += ["\\bottomrule", "\\end{tabular}", ""]
    return "\n".join(out)


def deployed_table(src: Path, extra: Sequence[Tuple[str, Path]] = (),
                   *, condition: str = "carryover_aware") -> str:
    """The closed-loop evaluation: the reference channel, then each read of each checkpoint.

    Takes one summary per backbone. Each brings its own lexical reference, because the reference
    is run inside that backbone's evaluation and must be compared against on its own terms.
    """
    blocks: List[Tuple[str, Dict[str, Any]]] = [("TinyVLA-2M", json.loads(src.read_text()))]
    for label, p in extra:
        if Path(p).exists():
            blocks.append((label, json.loads(Path(p).read_text())))
    return "\n".join([_stamp(src)] + [_deployed_block(label, d, condition, first=(i == 0))
                                      for i, (label, d) in enumerate(blocks)]
                     + ["\\bottomrule", "\\end{tabular}", ""])


def _deployed_block(label: str, data: Dict[str, Any], condition: str, *, first: bool) -> str:
    def cell(entry: Dict[str, Any], key: str) -> Any:
        return entry.get("conditions", {}).get(condition, {}).get(key, {}).get("mean")

    out: List[str] = []
    if first:
        out += ["\\begin{tabular}{@{}lllrrrrr@{}}", "\\toprule",
                "Backbone & Channel & Context & MAE$_\\times$ & regret & align & ungr. & abst./band \\\\",
                "\\midrule"]
    else:
        out.append("\\midrule")
    out.append(f"\\multicolumn{{8}}{{@{{}}l}}{{\\emph{{{label}}}}} \\\\")

    if "lexical" in data:
        e = data["lexical"]
        out.append(f" & lexical (ref.) & --- & {_f(cell(e, 'mae_crossover'))} "
                   f"& {_f(cell(e, 'deployment_regret'))} & {_f(cell(e, 'alignment'), 3)} "
                   f"& {_f(cell(e, 'n_ungrounded'), 1)} & --- \\\\")

    for read in ("policy_said", "policy_unprompted"):
        keys = [k for k in data if k.startswith(read + "@")]
        if not keys:
            continue
        keys.sort(key=lambda k: CONTEXT_ORDER.get(k.split("__")[-1], 9))
        read_label = "said" if read.endswith("said") else "unprompted"
        best = min((cell(data[k], "mae_crossover") for k in keys
                    if cell(data[k], "mae_crossover") is not None), default=None)
        for i, k in enumerate(keys):
            e = data[k]
            g = e.get("grounder", {})
            ctx = k.split("__")[-1] if "__" in k else k.split("@")[-1]
            mae = cell(e, "mae_crossover")
            maes = f"$\\mathbf{{{float(mae):.4f}}}$" if (mae is not None and mae == best) else _f(mae)
            head = (f"\\multirow{{{len(keys)}}}{{*}}{{\\textsf{{{read_label}}}}}" if i == 0 else "")
            out.append(f" & {head} & \\textsf{{{ctx}}} & {maes} & {_f(cell(e, 'deployment_regret'))} "
                       f"& {_f(cell(e, 'alignment'), 3)} & {_f(cell(e, 'n_ungrounded'), 1)} "
                       f"& {_f(g.get('abstain_rate'), 3)} / {_f(g.get('abstain_rate_band'), 3)} \\\\")
    return "\n".join(out)


def sensitivity_table(src: Path) -> str:
    """One row per setting of the assumptions; B1 bolded where it is worst, as it should be."""
    rows: List[Dict[str, Any]] = json.loads(src.read_text())
    # Present the dose ladder in dose order, not alphabetically: the interesting pattern is
    # monotone in the dose, and a reader should be able to see that by reading downwards.
    rank = {"dose_weak": 0, "dose_moderate": 1, "dose_strong": 2, "prior_flat": 3, "regime_alternating": 4}
    rows = sorted(rows, key=lambda r: rank.get(str(r.get("cell", "")), 99))
    order = ["memoryless", "fixed_washout", "random_static", "always_counter", "carryover_aware"]
    out = [_stamp(src), "\\begin{tabular}{lccccc c}", "\\toprule",
           "Setting & B1 & B2 & B3 & B4 & B5 & B5 ctr \\\\", "\\midrule"]
    for r in rows:
        vals = [r.get(k) for k in order]
        best = min((v for v in vals if v is not None), default=None)
        cells = []
        for v in vals:
            if v is None:
                cells.append("--")
            elif v == best:
                cells.append(f"\\textbf{{{v:.3f}}}")
            else:
                cells.append(f"{v:.3f}")
        ctr = r.get("carryover_aware__ctr")
        out.append(f"{r.get('label', r.get('cell', '?'))} & " + " & ".join(cells) +
                   f" & {ctr:.1f} \\\\" if ctr is not None else " & -- \\\\")
    out += ["\\bottomrule", "\\end{tabular}", ""]
    return "\n".join(out)


#: How the objective ablations are named in the paper, in the order they are discussed.
ABLATION_LABELS = {
    "full": ("every term", 0),
    "no-forward": ("without forward consistency", 1),
    "no-anti-copy": ("without the compliance penalty", 2),
    "no-reference": ("without reference supervision", 3),
}


def ablations_table(src: Path) -> str:
    """Which terms of the training objective are load-bearing."""
    rows: List[Dict[str, Any]] = json.loads(src.read_text())
    rows = [r for r in rows if r.get("debias_gain_brier") is not None]
    rows.sort(key=lambda r: ABLATION_LABELS.get(str(r.get("ablation")), ("", 9))[1])
    full = next((r for r in rows if r.get("ablation") == "full"), None)
    base = float(full["debias_gain_brier"]) if full else 0.0

    out = [_stamp(src), "\\begin{tabular}{@{}lrrr@{}}", "\\toprule",
           "Objective & Gain (Brier) & $\\Delta$ vs.\\ full & gap$\\sim\\kappa$ \\\\", "\\midrule"]
    for r in rows:
        label = ABLATION_LABELS.get(str(r.get("ablation")), (str(r.get("ablation")), 9))[0]
        g = float(r["debias_gain_brier"])
        d = "---" if r is full else f"${g - base:+.4f}$"
        out.append(f"{label} & {_f(g, 4, signed=True)} & {d} & {_f(r.get('debias_kappa_corr'), 3, signed=True)} \\\\")
    out += ["\\bottomrule", "\\end{tabular}", ""]
    return "\n".join(out)


def _ci(d: Dict[str, Any], nd: int = 4) -> str:
    """``$-0.0148$, CI $[-0.0248, -0.0046]$`` from a contrast entry.

    Emitted as a **text-mode** fragment with its own math delimiters, and wrapped in ``\mbox``
    so that writing ``$\MemorylessMAE$`` in the manuscript is an error rather than a silent
    disaster. Without the guard, the macro's first ``$`` closes the surrounding math, its last one
    re-opens it, and the remaining half-paragraph renders in italic maths --- which compiles
    cleanly and is only visible by reading the PDF.
    """
    return ("\\mbox{$%+.*f$, CI $[%+.*f, %+.*f]$}"
            % (nd, d["delta"], nd, d["lo"], nd, d["hi"]))


def headline_macros(src: Path) -> str:
    """``\newcommand``s for every number the abstract and introduction quote.

    The abstract, the introduction's findings list, the results text and the discussion all cite
    the same handful of contrasts. Typing them in four places is how a paper ends up disagreeing
    with itself after a re-run; here they are defined once from the study's own summary.
    """
    d: Dict[str, Any] = json.loads(src.read_text())
    conds = d.get("conditions", {})
    contr = d.get("contrasts", {})
    tr = d.get("test_retest", {})

    def mac(name: str, value: str) -> str:
        return f"\\newcommand{{\\{name}}}{{{value}}}"

    out = [_stamp(src)]
    out.append(mac("NSupervisors", str(int(d.get("n_supervisors", 0)))))
    floor = (tr.get("mae_crossover") or {}).get("mean")
    if floor is not None:
        out.append(mac("TestRetestFloor", f"{float(floor):.4f}"))
    for key, name in (("memoryless", "Memoryless"), ("always_counter", "AlwaysCounter"),
                      ("carryover_aware", "CarryoverAware"), ("random_static", "RandomStatic")):
        c = contr.get(key, {})
        if "mae_crossover" in c:
            out.append(mac(f"{name}MAE", _ci(c["mae_crossover"])))
        if "deployment_regret" in c:
            out.append(mac(f"{name}Regret", _ci(c["deployment_regret"], 4)))
        cell = conds.get(key, {})
        n_ctr = (cell.get("n_counter") or {}).get("mean")
        if n_ctr is not None:
            out.append(mac(f"{name}Counters", f"{float(n_ctr):.1f}"))
        mae = (cell.get("mae_crossover") or {}).get("mean")
        if mae is not None:
            out.append(mac(f"{name}AbsMAE", f"{float(mae):.4f}"))
    checks = ((d.get("audit") or {}).get("checks") or {})
    ident = checks.get("identified_fraction") or {}
    for k, name in (("lambda", "LambdaIdent"), ("beta_g", "BetaIdent")):
        if k in ident:
            out.append(mac(name, f"{float(ident[k]) * 100:.0f}"))
    src_phys = checks.get("physics_source")
    if src_phys:
        out.append(mac("PhysicsSource", str(src_phys)))
        out.append(mac("PhysicsRollouts", str(int(checks.get("physics_n_measured", 0)))))
    return "\n".join(out) + "\n"


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--models", type=Path, default=Path("vla_lab/results/models_isaac/table.json"))
    ap.add_argument("--models-extra", type=Path, nargs="*", default=[
        Path("vla_lab/results/models_isaac_smolvla/table.json"),
        Path("vla_lab/results/models_isaac_qwen/table.json"),
    ], help="further backbone sweeps to merge into the same table")
    ap.add_argument("--deployed", type=Path, default=Path("vla_lab/results/deployed/summary.json"))
    ap.add_argument("--sensitivity", type=Path, default=Path("vla_lab/results/sensitivity/table.json"))
    ap.add_argument("--study", type=Path, default=Path("vla_lab/results/tier1/summary.json"))
    ap.add_argument("--ablations", type=Path, default=Path("vla_lab/results/ablations/table.json"))
    ap.add_argument("--out", type=Path, default=PAPER / "tables")
    args = ap.parse_args(argv)

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    made, missing = [], []
    fns = {"tab_models.tex": lambda p: models_table(p, args.models_extra)}
    for name, src, fn in (("tab_models.tex", args.models, fns["tab_models.tex"]),
                          ("tab_deployed.tex", args.deployed,
                           lambda p: deployed_table(p, [("SmolVLA-450M",
                                                         Path("vla_lab/results/deployed_smolvla/summary.json"))])),
                          ("tab_sensitivity.tex", args.sensitivity, sensitivity_table),
                          ("tab_ablations.tex", args.ablations, ablations_table),
                          ("headline.tex", args.study, headline_macros)):
        if not Path(src).exists():
            missing.append(f"{name} <- {src}")
            continue
        (out / name).write_text(fn(Path(src)))
        made.append(f"{name} <- {src}")
    try:
        from .deployed_figure import figure as _deployed_figure

        if Path(args.deployed).exists():
            models = json.loads(Path(args.models).read_text()) if Path(args.models).exists() else []
            _deployed_figure(json.loads(Path(args.deployed).read_text()), models,
                             Path(args.deployed).parent / "fig_deployed.pdf")
            made.append("fig_deployed.pdf <- " + str(args.deployed))
    except Exception as exc:                                    # matplotlib is optional
        print(f"  (deployed figure skipped: {type(exc).__name__}: {exc})")
    for m in made:
        print("  wrote", m)
    for m in missing:
        print("  SKIPPED (source missing)", m)
    return 0 if not missing else 1


if __name__ == "__main__":
    raise SystemExit(main())
