"""Pick the three scenes the manuscript shows, and emit their gaps as LaTeX macros.

The figure that shows the task is three scenes: one where clearing first is the only option, one
at the crossover where the two strategies are worth the same, and one where reaching directly is
obviously fine. Which gaps those are is a *consequence* of the measured physics, so hard-coding
them into a caption guarantees that re-measuring the physics silently makes the caption wrong.
That already happened once here: the caption named a 6.9 cm crossover from the prior while the
measurement puts it at 8.5 cm.

So the images and the numbers come out of the same command:

    python -m vla_lab.supervisory.scene_strip

copies six PNGs into the paper's ``figures/`` and writes ``tables/scene_strip.tex`` defining
``\\SceneTightGap``, ``\\SceneCrossGap`` and ``\\SceneWideGap``, which the caption uses.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

PAPER = Path("vla_lab/paper/hri2027_carryover_vla")

#: (label, target coordinate). Positive ``c`` is the tight end -- see ``ScenePhysics.coordinate``.
PICKS: Tuple[Tuple[str, float], ...] = (("tight", 2.4), ("crossover", 0.0), ("wide", -2.4))


def choose(grid, picks: Sequence[Tuple[str, float]] = PICKS) -> Dict[str, object]:
    """Nearest probe scene to each target coordinate, never reusing one."""
    out: Dict[str, object] = {}
    used: set = set()
    probes = [s for s in grid.scenes if not getattr(s, "is_coach", False)] or list(grid.scenes)
    for name, c in picks:
        cand = sorted((s for s in probes if s.scene_id not in used), key=lambda s: abs(float(s.c) - c))
        if not cand:
            continue
        out[name] = cand[0]
        used.add(cand[0].scene_id)
    return out


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--frames", type=Path, default=Path("vla_lab/results/physics/frames"))
    ap.add_argument("--figures", type=Path, default=PAPER / "figures")
    ap.add_argument("--tables", type=Path, default=PAPER / "tables")
    ap.add_argument("--variant", default="v0")
    args = ap.parse_args(argv)

    from .scenes import build_scene_grid

    grid = build_scene_grid()
    chosen = choose(grid)
    args.figures.mkdir(parents=True, exist_ok=True)
    args.tables.mkdir(parents=True, exist_ok=True)

    macro = {"tight": "SceneTightGap", "crossover": "SceneCrossGap", "wide": "SceneWideGap"}
    lines: List[str] = [
        "% generated by vla_lab.supervisory.scene_strip -- do not edit by hand",
        f"\\newcommand{{\\SceneCrossoverMargin}}{{{grid.physics.crossover_margin() * 100:.1f}}}",
    ]
    missing: List[str] = []
    for name, scene in chosen.items():
        for view, prefix in (("figure", "scene"), ("topdown", "top")):
            src = args.frames / view / f"scene_{int(scene.scene_id):03d}" / f"{args.variant}.png"
            dst = args.figures / f"{prefix}_{name}.png"
            if src.exists():
                shutil.copy(src, dst)
            else:
                missing.append(str(src))
        lines.append(f"\\newcommand{{\\{macro[name]}}}{{{float(scene.margin_m) * 100:.1f}}}")
        print(f"  {name:10s} scene {scene.scene_id:2d}  c={float(scene.c):+.2f}  "
              f"gap={float(scene.margin_m) * 100:.1f} cm")

    (args.tables / "scene_strip.tex").write_text("\n".join(lines) + "\n")
    print(f"physics source: {grid.physics.source}; crossover {grid.physics.crossover_margin() * 100:.1f} cm")
    for m in missing:
        print("  MISSING", m)
    return 0 if not missing else 1


if __name__ == "__main__":
    raise SystemExit(main())
