#!/usr/bin/env bash
# ★ Refresh every figure the manuscript includes from the results that produced it.
#
#   ./vla_lab/scripts/sync_paper_figures.sh
#
# A stale figure is the quietest way for a paper to disagree with its own numbers: the caption
# is regenerated by hand, the plot is not, and nothing warns. This copies each one from its
# canonical result directory and reports the age of what it copied, so a figure that predates
# the run it claims to show is visible at a glance.
set -uo pipefail
REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"; cd "${REPO_ROOT}"
DEST="vla_lab/paper/hri2027_carryover_vla/figures"
mkdir -p "${DEST}"

copy() {  # copy <src> <dest-name>
  if [[ -f "$1" ]]; then
    cp "$1" "${DEST}/$2"
    printf '  %-26s <- %-56s (%s)\n' "$2" "$1" "$(date -r "$1" '+%Y-%m-%d %H:%M')"
  else
    printf '  %-26s ** MISSING ** %s\n' "$2" "$1"
    MISSING=$((MISSING + 1))
  fi
}

MISSING=0
echo "syncing manuscript figures:"
copy vla_lab/results/tier1/fig_primary.pdf        fig_primary.pdf
copy vla_lab/results/tier1/fig_carryover.pdf      fig_carryover.pdf
copy vla_lab/results/tier1/fig_frontier.pdf       fig_frontier.pdf
copy vla_lab/results/tier1/fig_heterogeneity.pdf  fig_heterogeneity.pdf
copy vla_lab/results/sensitivity/fig_sensitivity.pdf fig_sensitivity.pdf
copy vla_lab/results/physics/fig_physics.pdf      fig_physics.pdf
copy vla_lab/results/reach/fig_reach.pdf          fig_reach.pdf
copy vla_lab/results/deployed/fig_deployed.pdf    fig_deployed.pdf
copy "${AUDIT_DIR:-vla_lab/results/models_isaac/audit}/fig_training_curves.pdf" fig_training_curves.pdf
copy vla_lab/results/flip_w/fig_flip.pdf              fig_flip_w.pdf
copy vla_lab/results/flip_mstar/fig_flip.pdf          fig_flip_mstar.pdf
copy vla_lab/results/sensitivity/fig_dose_tracking.pdf fig_dose_tracking.pdf
copy vla_lab/results/tier1/fig_identification.pdf    fig_identification.pdf
echo
echo "regenerating the manuscript's measured tables:"
python -m vla_lab.supervisory.latex_tables || true
echo
echo "re-extracting the scene strip (images and their gaps come from the same command):"
python -m vla_lab.supervisory.scene_strip || true
echo
# The exit status is reported last, after everything that *can* be refreshed has been: a missing
# figure should not stop the tables from being regenerated, or a half-synced paper is the result.
if [[ ${MISSING} -gt 0 ]]; then
  echo "${MISSING} figure(s) missing -- run the stage that produces them before building the paper."
  exit 1
fi
echo "all manuscript figures refreshed."
